/* Minimal set of SUNDIALS configuration variables */
#define SUNDIALS_VERSION "5.3.0"
#define SUNDIALS_VERSION_MAJOR 5
#define SUNDIALS_VERSION_MINOR 3
#define SUNDIALS_VERSION_PATCH 0
#define SUNDIALS_VERSION_LABEL ""
#define SUNDIALS_F77_FUNC(name,NAME) name ## _
#define SUNDIALS_DOUBLE_PRECISION 1
#define SUNDIALS_INT32_T 1
#define SUNDIALS_INDEX_TYPE int32_t
#define SUNDIALS_USE_GENERIC_MATH 1
/* #undef SUNDIALS_BLAS_LAPACK */
#define SUNDIALS_EXPORT
#define SUNDIALS_DEPRECATED SUNDIALS_EXPORT
